# Generated by Django 2.2.6 on 2023-05-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_auto_20230509_1726'),
        ('jedzonko', '0009_merge_20230510_0912'),
    ]

    operations = [
    ]
